### ISSUE TITLE
automated file hasher

### ISSUE THREAD

**Issue by charlesdublend360** [BLEND360/innovation_lab#7]
We need to create an interactive platform for users to send data to india. 

Should create an interactive dashboard that allows delivery leads to select PII columns for them to be scrambled and send to india.

**Comment by slowtacocar** [comment]
@charlesdublend360 I have the code I wrote for this a while back. I should have some time today to work on getting it in dashboard form; I'll let you know how it goes.

**Comment by charlesdublend360** [comment]
@moonziyue work with Bobby to develop the product further
